### PR TITLE
Added VERSION file

### LINKED ISSUE #115: Version number
**Is your feature request related to a problem? Please describe.**

Would be a smart idea of have some form of VERSION file that we can read in to determine what version of limbus is being run. Would also help with CD.

**Describe the solution you'd like**
A file called VERSION in app that just says what version is being run. We could then read this in and have it as a global variable that can be used when rendering templates and such.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pramod74**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #115

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KeironO — COMMENTED** [review]
Not quite what I wanted.

**Comment by KeironO** [comment]
https://pypi.org/project/semantic-version/

**Comment by pramod74** [comment]
Hi @KeironO,

Thanks for sharing the helpful link and for reviewing my earlier submission.

It seems as if including the following line in VERSION file should help:
[VERSION.zip](https://github.com/AberystwythSystemsBiology/limbus/files/7884250/VERSION.zip)


__version__ = "20.08.0"

Then, the version can be read from within other files in the repository using code similar to the following:

with open(os.path.join(mypackage_root_dir, 'VERSION')) as version_file:
    version = version_file.read().strip()

Please suggest if this would help. If yes, I shall submit another PR with this update to the VERSION file contents.

Thanks,
Pramod

**Comment by KeironO** [comment]
Hi @pramod74 

Thank you for the contribution.

Unfortunately I'm unable to accept this PR account of me not fully understanding how semantic versioning is supposed to be implemented. This is by no means a reflection on your submission, it could be that this worked - but with this being such an important project in a healthcare setting I don't want to implement things without fully understanding them first.

Best wishes,

Keiron

**Comment by pramod74** [comment]
Hi @KeironO,

No issues. I understand your concern.
Thanks for your guidance. I look forward to working with you on some other issue.

Thanks,
Pramod

**Pull request closed without merging**
