### PR TITLE
general improvements based on user feedback

### PR DESCRIPTION
**Pull request by pipaLU**
## Description
General improvement in functionality and usability and bug fixing based on user feedback. 

New features:
- Shallow and deep sample/event removal.
- Sample derivation 
- Allow adding source study info to sample consent. (table changes, adding new table donor_protocol_event)
- Drag n drop rack sample position edit. 
- New/Edit rack sample from csv file
- Edit consent/sample basic info.
- Customisable user settings to reduce workload of data entry (default values for protocol templates/consent form template, sample/container types)
- Sample/container type order in dropdown list adaptable based on database records
- Sample Shipment with protocol info
- Site info edit, allowing external sites, and multiple addresses for each site
- Access control for sites
- Audit report for sample/donor/protocol or form templates/user
- Batch sample review and disposal

Fixes # (issue)
- Dealing with csv files of multiple platforms
- ...

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by KeironO** [comment]
Hi Chuan,

I am unable to accept the pull request:

```
Run docker-compose run web sh -c "flask cmd_setup create-kryten"
Creating limbus_web_run ... 
Creating limbus_web_run ... done
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship UserAccountVersion.version_parent to refer to viewonly relationship UserAccount.versions will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship UserAccount.versions to refer to viewonly relationship UserAccountVersion.version_parent will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship AddressVersion.version_parent to refer to viewonly relationship Address.versions will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship SiteInformation.versions to refer to viewonly relationship SiteInformationVersion.version_parent will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship EventVersion.version_parent to refer to viewonly relationship Event.versions will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship Event.versions to refer to viewonly relationship EventVersion.version_parent will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship ConsentFormTemplateVersion.version_parent to refer to viewonly relationship ConsentFormTemplate.versions will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship ConsentFormTemplateQuestion.versions to refer to viewonly relationship ConsentFormTemplateQuestionVersion.version_parent will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship ProtocolTemplate.versions to refer to viewonly relationship ProtocolTemplateVersion.version_parent will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/relationships.py:1917: SAWarning: Setting backref / back_populates on relationship SampleProtocolEventVersion.version_parent to refer to viewonly relationship SampleProtocolEvent.versions will be deprecated in SQLAlchemy 1.4, and will be disallowed in a future release.  viewonly relationships should not be mutated (this warning may be suppressed after 10 occurrences)
  (self, other),
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/limbus/app/__init__.py", line 59, in create_app
    app.config.from_pyfile("config.py")
  File "/usr/local/lib/python3.6/dist-packages/flask/config.py", line 131, in from_pyfile
    with open(filename, mode="rb") as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/instance/config.py'
1
Error: Process completed with exit code 1.
```

Have you moved the config.py file?

**Comment by pipaLU** [comment]
Strange,I didn't touch config.py at all

**Comment by KeironO** [comment]
I'll have to take a look this evening. I should be finished at around 5pm.

Edit: @rob-a-bolton is having a quick look at it as it looks a bit strange.

**Comment by KeironO** [comment]
@rob-a-bolton has taken a look and it's showing the same error on his machine.

I'll sort it > 5pm

**Comment by KeironO** [comment]
Thank you @rob-a-bolton for highlighting a recent change to Flask that makes lazy-loading config files no longer work:

> Flask for a long time made it possible to refer to paths relative to the application’s folder directly (via Flask.root_path). This was also how many developers loaded configurations stored next to the application. Unfortunately however this only works well if applications are not packages in which case the root path refers to the contents of the package.
With Flask 0.8 a new attribute was introduced: Flask.instance_path. It refers to a new concept called the “instance folder”. The instance folder is designed to not be under version control and be deployment specific. It’s the perfect place to drop things that either change at runtime or configuration files.
You can either explicitly provide the path of the instance folder when creating the Flask application or you can let Flask autodetect the instance folder. For explicit configuration use the instance_path parameter:


```
app = Flask(__name__, instance_path='/path/to/instance/folder')
```

This change requires users to add a `INSTANCE_PATH` path to their `.env` file. This will need documentation.

The document tests fail at the moment, so I'll have to take a look at what's happening there before merging the PR.

**Comment by KeironO** [comment]
I really dislike Python.

So, it turns out that nose doesn't run tests in the order they are present in a class - nope.

It's alphabetical.

This **should** fix it:

image

I hate everything.

**Comment by KeironO** [comment]
Also, it'd be useful to maybe only have one build go on for CI - I'll sort this out in another PR once this is merged.

**Review by KeironO — APPROVED** [review]

**Comment by KeironO** [comment]
Merged.

**Pull request merged**
